security:
    password_hashers:
        # auto hasher with custom options for all PasswordAuthenticatedUserInterface instances
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'plaintext'
        Symfony\Component\Security\Core\User\User:
            algorithm: 'plaintext'

    providers:
        backend_users:
            memory:
                users:
                    admin: { password: 'test', roles: ['ROLE_ADMIN'] }

    firewalls:
        main:
            provider: backend_users
            # Add the appropriate authentication method (e.g., form_login or http_basic)
            # For simplicity, we'll use HTTP Basic Authentication here
            http_basic: ~

    access_control:
        # Example access control rule
        - { path: ^/api/, roles: ROLE_ADMIN, methods: [POST, PATCH, DELETE] }
